POST {{servico_processamento}}/pesquisas/criar
Content-Type: application/json

{
  "codigo": "BF200",
  "inicio": "2025-01-23T14:00:00",
  "fim": "2025-01-26T17:00:00"
}

###
GET {{servico_processamento}}/pesquisas/67a21abcfa2d601b260b466/obter

###
PATCH {{servico_processamento}}/pesquisas/atualizar
Content-Type: application/json

{
  "id": "67a21f50a71f07355412e454",
  "codigo": "333",
  "inicio": "2025-01-26T00:00:00",
  "fim": "2025-01-26T00:00:00"
}

###
DELETE {{servico_processamento}}/pesquisas/67a2163aa1020d17c047d2ad/remover

###
POST {{servico_processamento}}/pesquisas/criar
Content-Type: application/json

{
  "nome": "João Mendes",
  "email": "joao@email.com",
  "idade": 25
}