POST {{servico_processamento}}/pesquisas/criar
Content-Type: application/json

{
  "codigo": "573",
  "inicio": "2025-01-14T14:49:34",
  "fim": "2025-01-17T00:00:00"
}

###
GET {{servico_processamento}}/pesquisas/678a8c9c4c6f35b4ac3c8687/obter

###
PATCH {{servico_processamento}}/pesquisas/atualizar
Content-Type: application/json

{
  "id": "678a91b56a2e316c0310a99d",
  "codigo": "575",
  "inicio": "2025-01-22T08:00:00",
  "fim": "2025-01-26T00:00:00"
}

###
DELETE {{servico_processamento}}/pesquisas/6789e23da85c066d20f2a1f6/remover

###
POST {{servico_processamento}}/pesquisas/criar
Content-Type: application/json

{
  "nome": "João Mendes",
  "email": "joao@email.com",
  "idade": 25
}